# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Neighborhood
                                 A QGIS plugin
 This plugin selects the polygons adjacent to a given polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-06
        copyright            : (C) 2021 by Salomón Ramírez / Universidad Distrital Francisco José de Caldas
        email                : seramirezf@correo.udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Neighborhood class from file Neighborhood.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .neighbor import Neighborhood
    return Neighborhood(iface)
